package com.one.conversormonedas.enums;

public enum Moneda {
  AED("Dirham de los Emiratos Árabes Unidos"),
  AFN("Afghani afgano"),
  ALL("Lek albanés"),
  AMD("Dram armenio"),
  ANG("Florín de las Antillas Neerlandesas"),
  AOA("Kwanza angoleño"),
  ARS("Peso argentino"),
  AUD("Dólar australiano"),
  AWG("Florín arubeño"),
  AZN("Manat azerbaiyano"),
  BAM("Marco convertible de Bosnia y Herzegovina"),
  BBD("Dólar barbadense"),
  BDT("Taka bangladesí"),
  BGN("Lev búlgaro"),
  BHD("Dinar bahreiní"),
  BIF("Franco burundés"),
  BMD("Dólar bermudeño"),
  BND("Dólar de Brunéi"),
  BOB("Boliviano boliviano"),
  BRL("Real brasileño"),
  BSD("Dólar bahameño"),
  BTN("Ngultrum butanés"),
  BWP("Pula botsuano"),
  BYN("Rublo bielorruso"),
  BZD("Dólar beliceño"),
  CAD("Dólar canadiense"),
  CDF("Franco congoleño"),
  CHF("Franco suizo"),
  CLP("Peso chileno"),
  CNY("Renminbi chino"),
  COP("Peso colombiano"),
  CRC("Colón costarricense"),
  CUP("Peso cubano"),
  CVE("Escudo caboverdiano"),
  CZK("Corona checa"),
  DJF("Franco yibutiano"),
  DKK("Corona danesa"),
  DOP("Peso dominicano"),
  DZD("Dinar argelino"),
  EGP("Libra egipcia"),
  ERN("Nakfa eritreo"),
  ETB("Birr etíope"),
  EUR("Euro"),
  FJD("Dólar fiyiano"),
  FKP("Libra de las Islas Malvinas"),
  FOK("Corona feroesa"),
  GBP("Libra esterlina"),
  GEL("Lari georgiano"),
  GGP("Libra de Guernsey"),
  GHS("Cedi ghanés"),
  GIP("Libra de Gibraltar"),
  GMD("Dalasi gambiano"),
  GNF("Franco guineano"),
  GTQ("Quetzal guatemalteco"),
  GYD("Dólar guyanés"),
  HKD("Dólar de Hong Kong"),
  HNL("Lempira hondureña"),
  HRK("Kuna croata"),
  HTG("Gourde haitiano"),
  HUF("Florín húngaro"),
  IDR("Rupia indonesia"),
  ILS("Nuevo shéquel israelí"),
  IMP("Libra de la Isla de Man"),
  INR("Rupia india"),
  IQD("Dinar iraquí"),
  IRR("Rial iraní"),
  ISK("Corona islandesa"),
  JEP("Libra de Jersey"),
  JMD("Dólar jamaicano"),
  JOD("Dinar jordano"),
  JPY("Yen japonés"),
  KES("Chelín keniano"),
  KGS("Som kirguís"),
  KHR("Riel camboyano"),
  KID("Dólar de Kiribati"),
  KMF("Franco comorano"),
  KRW("Won surcoreano"),
  KWD("Dinar kuwaití"),
  KYD("Dólar de las Islas Caimán"),
  KZT("Tenge kazajo"),
  LAK("Kip laosiano"),
  LBP("Libra libanesa"),
  LKR("Rupia de Sri Lanka"),
  LRD("Dólar liberiano"),
  LSL("Loti lesotense"),
  LYD("Dinar libio"),
  MAD("Dirham marroquí"),
  MDL("Leu moldavo"),
  MGA("Ariary malgache"),
  MKD("Dinar macedonio"),
  MMK("Kyat birmano"),
  MNT("Tögrög mongol"),
  MOP("Pataca macaense"),
  MRU("Ouguiya mauritana"),
  MUR("Rupia mauricia"),
  MVR("Rufiyaa maldiva"),
  MWK("Kwacha malauí"),
  MXN("Peso mexicano"),
  MYR("Ringgit malasio"),
  MZN("Metical mozambiqueño"),
  NAD("Dólar namibio"),
  NGN("Naira nigeriana"),
  NIO("Córdoba nicaragüense"),
  NOK("Corona noruega"),
  NPR("Rupia nepalesa"),
  NZD("Dólar neozelandés"),
  OMR("Rial omaní"),
  PAB("Balboa panameño"),
  PEN("Sol peruano"),
  PGK("Kina de Papúa Nueva Guinea"),
  PHP("Peso filipino"),
  PKR("Rupia paquistaní"),
  PLN("Złoty polaco"),
  PYG("Guaraní paraguayo"),
  QAR("Riyal catarí"),
  RON("Leu rumano"),
  RSD("Dinar serbio"),
  RUB("Rublo ruso"),
  RWF("Franco ruandés"),
  SAR("Riyal saudí"),
  SBD("Dólar de las Islas Salomón"),
  SCR("Rupia seychellense"),
  SDG("Libra sudanesa"),
  SEK("Corona sueca"),
  SGD("Dólar singapurense"),
  SHP("Libra de Santa Elena"),
  SLE("Leona de Sierra Leona"),
  SOS("Chelín somalí"),
  SRD("Dólar surinamés"),
  SSP("Libra sursudanesa"),
  STN("Dobra de Santo Tomé y Príncipe"),
  SYP("Libra siria"),
  SZL("Lilangeni suazi"),
  THB("Baht tailandés"),
  TJS("Somoni tayiko"),
  TMT("Manat turcomano"),
  TND("Dinar tunecino"),
  TOP("Paʻanga tongano"),
  TRY("Lira turca"),
  TTD("Dólar de Trinidad y Tobago"),
  TVD("Dólar de Tuvalu"),
  TWD("Nuevo dólar taiwanés"),
  TZS("Chelín tanzano"),
  UAH("Grivna ucraniana"),
  UGX("Chelín ugandés"),
  USD("Dólar estadounidense"),
  UYU("Peso uruguayo"),
  UZS("Som uzbeko"),
  VES("Bolívar soberano venezolano"),
  VND("Dong vietnamita"),
  VUV("Vatu vanuatuense"),
  WST("Tala samoano"),
  XAF("Franco CFA de África Central"),
  XCD("Dólar del Caribe Oriental"),
  XDR("Derechos Especiales de Giro"),
  XOF("Franco CFA de África Occidental"),
  XPF("Franco CFP"),
  YER("Rial yemení"),
  ZAR("Rand sudafricano"),
  ZMW("Kwacha zambiano"),
  ZWL("Dólar zimbabuense");

  private final String nombreMoneda;

  Moneda(String nombreMoneda) {
    this.nombreMoneda = nombreMoneda;
  }

  public String getNombreMoneda() {
    return nombreMoneda;
  }
}

